buildscript {
    ext.kotlin_version = '1.5.31'
    ext {
        roomVersion = '2.4.2'
        coroutineVersion = '1.5.2'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // Добавили JitPack
        jcenter() // Вернули для старых библиотек
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // И здесь тоже
        jcenter() 
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
