buildscript {
    ext.kotlin_version = '1.5.31'
    ext {
        // Добавляем версии, которые ищет файл в папке app
        roomVersion = '2.4.2'
        coroutineVersion = '1.5.2'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
